"""slice 1 foundation schema

Revision ID: 2fddfa08e7c5
Revises: 
Create Date: 2026-07-27 11:24:32.879060
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2fddfa08e7c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_fetches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('capability', sa.String(length=40), nullable=False),
    sa.Column('endpoint', sa.String(length=160), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('actual_cost', sa.Float(), nullable=False),
    sa.Column('raw_payload_uri', sa.String(length=500), nullable=False),
    sa.Column('raw_payload_hash', sa.String(length=64), nullable=False),
    sa.Column('parser_version', sa.String(length=40), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('linked_entity_ids', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_fetches_capability'), 'provider_fetches', ['capability'], unique=False)
    op.create_index(op.f('ix_provider_fetches_provider'), 'provider_fetches', ['provider'], unique=False)
    op.create_index(op.f('ix_provider_fetches_request_fingerprint'), 'provider_fetches', ['request_fingerprint'], unique=False)
    op.create_table('provider_health',
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('capability', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('window_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('p50_latency_ms', sa.Integer(), nullable=False),
    sa.Column('p95_latency_ms', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('circuit_state', sa.String(length=24), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('provider', 'capability')
    )
    op.create_table('topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical_label', sa.String(length=300), nullable=False),
    sa.Column('aliases_json', sa.JSON(), nullable=False),
    sa.Column('entities_json', sa.JSON(), nullable=False),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lifecycle_stage', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('merged_into_topic_id', sa.String(length=36), nullable=True),
    sa.Column('clustering_version', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('plan', sa.String(length=40), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('youtube_channels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('youtube_channel_id', sa.String(length=64), nullable=False),
    sa.Column('canonical_url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('default_language', sa.String(length=16), nullable=False),
    sa.Column('subscriber_count', sa.Integer(), nullable=False),
    sa.Column('video_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youtube_channels_youtube_channel_id'), 'youtube_channels', ['youtube_channel_id'], unique=True)
    op.create_table('channel_baselines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('window', sa.String(length=24), nullable=False),
    sa.Column('metric_name', sa.String(length=80), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['youtube_channels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'window', 'metric_name', 'version')
    )
    op.create_table('demand_clusters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('taxonomy', sa.String(length=80), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('distinct_video_count', sa.Integer(), nullable=False),
    sa.Column('distinct_channel_count', sa.Integer(), nullable=False),
    sa.Column('demand_score', sa.Float(), nullable=False),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_provenance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('field_name', sa.String(length=120), nullable=False),
    sa.Column('provider_fetch_id', sa.String(length=36), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('value_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['provider_fetch_id'], ['provider_fetches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('lifecycle_stage', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(length=24), nullable=False),
    sa.Column('opportunity_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opportunity_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=False),
    sa.Column('why_emerging_json', sa.JSON(), nullable=False),
    sa.Column('component_json', sa.JSON(), nullable=False),
    sa.Column('evidence_version', sa.String(length=40), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id')
    )
    op.create_table('topic_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('video_count_24h', sa.Integer(), nullable=False),
    sa.Column('video_count_72h', sa.Integer(), nullable=False),
    sa.Column('distinct_channels_72h', sa.Integer(), nullable=False),
    sa.Column('aggregate_view_velocity', sa.Float(), nullable=False),
    sa.Column('median_outlier_ratio', sa.Float(), nullable=False),
    sa.Column('large_channel_count', sa.Integer(), nullable=False),
    sa.Column('demand_score', sa.Float(), nullable=False),
    sa.Column('saturation_score', sa.Float(), nullable=False),
    sa.Column('fragility_score', sa.Float(), nullable=False),
    sa.Column('component_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'observed_at')
    )
    op.create_table('workspace_channels',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('relationship', sa.String(length=24), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['youtube_channels.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('workspace_id', 'channel_id')
    )
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('workspace_id', 'user_id')
    )
    op.create_table('youtube_videos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('canonical_url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('default_language', sa.String(length=16), nullable=False),
    sa.Column('category_id', sa.String(length=16), nullable=False),
    sa.Column('is_short', sa.Boolean(), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=False),
    sa.Column('first_discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['youtube_channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youtube_videos_published_at'), 'youtube_videos', ['published_at'], unique=False)
    op.create_index(op.f('ix_youtube_videos_youtube_video_id'), 'youtube_videos', ['youtube_video_id'], unique=True)
    op.create_table('content_briefs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('signal_id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('brief_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['youtube_channels.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('signal_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_video_memberships',
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('membership_score', sa.Float(), nullable=False),
    sa.Column('assignment_method', sa.String(length=40), nullable=False),
    sa.Column('evidence_role', sa.String(length=40), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['youtube_videos.id'], ),
    sa.PrimaryKeyConstraint('topic_id', 'video_id')
    )
    op.create_table('video_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('video_age_seconds', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('views_per_hour', sa.Float(), nullable=False),
    sa.Column('snapshot_quality', sa.String(length=24), nullable=False),
    sa.Column('provider_fetch_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['provider_fetch_id'], ['provider_fetches.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['youtube_videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'observed_at')
    )
    op.create_index(op.f('ix_video_snapshots_observed_at'), 'video_snapshots', ['observed_at'], unique=False)
    op.create_table('video_transcripts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('transcript_type', sa.String(length=24), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('provider_fetch_id', sa.String(length=36), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('generated_cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_fetch_id'], ['provider_fetches.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['youtube_videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    op.create_table('workspace_signal_scores',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('signal_id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('channel_fit_score', sa.Float(), nullable=False),
    sa.Column('fit_component_json', sa.JSON(), nullable=False),
    sa.Column('recommended_angle_json', sa.JSON(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['youtube_channels.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('workspace_id', 'signal_id')
    )
    op.create_table('youtube_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_comment_id', sa.String(length=100), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('parent_comment_id', sa.String(length=36), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('is_reply', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('normalized_hash', sa.String(length=64), nullable=False),
    sa.Column('provider_fetch_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_fetch_id'], ['provider_fetches.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['youtube_videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_comment_id', 'video_id')
    )
    op.create_index('ix_comment_normalized_hash', 'youtube_comments', ['normalized_hash'], unique=False)
    op.create_table('demand_cluster_comments',
    sa.Column('demand_cluster_id', sa.String(length=36), nullable=False),
    sa.Column('comment_id', sa.String(length=36), nullable=False),
    sa.Column('membership_score', sa.Float(), nullable=False),
    sa.Column('is_representative', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['youtube_comments.id'], ),
    sa.ForeignKeyConstraint(['demand_cluster_id'], ['demand_clusters.id'], ),
    sa.PrimaryKeyConstraint('demand_cluster_id', 'comment_id')
    )
    op.create_table('published_outcomes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('signal_id', sa.String(length=36), nullable=False),
    sa.Column('content_brief_id', sa.String(length=36), nullable=True),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('baseline_definition', sa.String(length=240), nullable=False),
    sa.Column('performance_json', sa.JSON(), nullable=False),
    sa.Column('success_status', sa.String(length=32), nullable=False),
    sa.Column('user_notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_brief_id'], ['content_briefs.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('published_outcomes')
    op.drop_table('demand_cluster_comments')
    op.drop_index('ix_comment_normalized_hash', table_name='youtube_comments')
    op.drop_table('youtube_comments')
    op.drop_table('workspace_signal_scores')
    op.drop_table('video_transcripts')
    op.drop_index(op.f('ix_video_snapshots_observed_at'), table_name='video_snapshots')
    op.drop_table('video_snapshots')
    op.drop_table('topic_video_memberships')
    op.drop_table('signal_actions')
    op.drop_table('content_briefs')
    op.drop_index(op.f('ix_youtube_videos_youtube_video_id'), table_name='youtube_videos')
    op.drop_index(op.f('ix_youtube_videos_published_at'), table_name='youtube_videos')
    op.drop_table('youtube_videos')
    op.drop_table('workspace_members')
    op.drop_table('workspace_channels')
    op.drop_table('topic_snapshots')
    op.drop_table('signals')
    op.drop_table('field_provenance')
    op.drop_table('demand_clusters')
    op.drop_table('channel_baselines')
    op.drop_index(op.f('ix_youtube_channels_youtube_channel_id'), table_name='youtube_channels')
    op.drop_table('youtube_channels')
    op.drop_table('workspaces')
    op.drop_table('users')
    op.drop_table('topics')
    op.drop_table('provider_health')
    op.drop_index(op.f('ix_provider_fetches_request_fingerprint'), table_name='provider_fetches')
    op.drop_index(op.f('ix_provider_fetches_provider'), table_name='provider_fetches')
    op.drop_index(op.f('ix_provider_fetches_capability'), table_name='provider_fetches')
    op.drop_table('provider_fetches')
    # ### end Alembic commands ###

